server:
  port: 3000
  forward-headers-strategy: native # 프록시 서버 헤더를 신뢰하도록 설정

spring:
  application:
    name: no1delivery

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}

# JWT 설정
jwt:
  secret: ${JSON_WEB_TOKEN_SECRET}
  valid-time: ${JSON_WEB_TOKEN_VALID_TIME:3600}

  logging:
    level:
      org.hibernate.type: trace
      org.hibernate.orm.jdbc.bind: trace