spring:
  application:
    name: no1delivery

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}

# JWT 설정
jwt:
  secret: ${JSON_WEB_TOKEN_SECRET}
  valid-time: ${JSON_WEB_TOKEN_VALID_TIME:3600}

  logging:
    level:
      org.hibernate.type: trace
      org.hibernate.orm.jdbc.bind: trace